### ISSUE TITLE
Passwort fehlt aber man kann keines eintippen

### ISSUE THREAD

**Issue by MisterMister64** [Samedis-care/identity-management-frontend#4]
![grafik](https://github.com/Samedis-care/identity-management-frontend/assets/109486506/1fba67be-54d8-466e-8897-e620b1503059)

Wenn man versucht hier einen neuen Nutzer anzulegen, wird man damit abgewiesen, dass kein Passwort eingegeben wurde obwohl man keines eintippen kann.

**Comment by neongrau** [comment]
Das hatten wir irgendwann mal entfernt da hier email validierung übergangen wird was nicht länger erwünscht war.
Backend hat jetz einen Fix via https://github.com/Samedis-care/identity-management-backend/commit/14fab2041a9ab51b5c2a2cca091e121259b40058

@SCjona das benötigt zusätzlich noch das im Frontend ein `set_password` Feld eingebaut wird (keine Wiederholung da administrativ)
